# Generated by Django 4.2.3 on 2023-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productsize_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='sizes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
