# Generated by Django 4.2.3 on 2023-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_image_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='image',
            field=models.FileField(upload_to='product_images'),
        ),
    ]
