# Generated by Django 4.2.3 on 2023-08-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_productsize_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('One Size', 'ONE SIZE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productsizemapping',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='products.productsize'),
        ),
    ]
