# Generated by Django 4.2.3 on 2023-07-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_basket_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='sizes',
            new_name='size',
        ),
    ]
