# Generated by Django 4.2.3 on 2023-08-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_quantity_productsize_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productsizemapping',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
