# Generated by Django 4.2.3 on 2023-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_productsize_name_alter_productsizemapping_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='image',
            field=models.FileField(upload_to='media/product_images'),
        ),
    ]
